[phases.setup]
nixPkgs = ["nodejs_18", "npm"]

[phases.install]
cmds = ["cd backend && npm install"]

[phases.build]
cmds = ["echo 'Backend ready, no build step needed'"]

[start]
cmd = "cd backend && npm start"